Fix bug causing plot_channel_maps(..) to break when textcolor='notext' set
radio-astro-tools/spectral-cube pull request #690
Opened 2020-11-25 18:52 UTC by drtobybrown

Fixes issue #689

2020-11-25 20:55 UTC, keflavich requested changes
small change: I think the ticks pointing in should happen either way.

But, otherwise, this looks good

2020-11-25 20:55 UTC, keflavich commented on spectral_cube/spectral_cube.py
> +                ax.tick_params(direction='in', color=textcolor)
```suggestion
                ax.tick_params(color=textcolor)
```

2020-11-25 20:55 UTC, keflavich commented on spectral_cube/spectral_cube.py
> -            ax.tick_params(direction='in', color=textcolor)
suggestion:
```
            ax.tick_params(direction='in')
```

2020-11-25 22:58 UTC, e-koch commented
I think all the test failures here are a carryover from #688

2020-12-07 16:59 UTC, keflavich commented
I'm merging this from the command line with one additional small tweak; unfortunately I can't push to this branch so I'm kinda crossing my fingers that I didn't break the build by removing whitespace and re-adding the ticks-in

2020-12-07 16:59 UTC, keflavich commented
This has been merged despite github's complaints.

2020-12-07 16:59 UTC, closed without merging