Add reproject docs
radio-astro-tools/spectral-cube pull request #771
Opened 2021-11-20 18:06 UTC by keflavich

Solves #590.

It might be helpful to add a little more documentation, but the basics are here and the reference to [reproject](https://reproject.readthedocs.io/en/stable/) is perhaps enough to get people going.

2021-11-20 19:05 UTC, e-koch requested changes
Minor changes. Then good to go.

2021-11-20 19:05 UTC, e-koch commented on docs/smoothing.rst
> +Spatial reprojection can be achieved with the `SpectralCube.reproject` method::
```suggestion
Spatial reprojection can be achieved with the :class:`~spectral_cube.SpectralCube.reproject` method::
```
Unsure if this is still needed to generate the link.

2021-11-20 19:05 UTC, e-koch commented on docs/smoothing.rst
> +<https://reproject.readthedocs.io/en/stable/>`_ model to regrid each channel.
```suggestion
<https://reproject.readthedocs.io/en/stable/>`_ package to regrid each channel.
```

2021-11-20 19:05 UTC, e-koch commented on docs/smoothing.rst
> +<https://github.com/radio-astro-tools/tutorials/pull/17>`_.
Maybe add a commented-out note that we should change this link once the PR is merged.

2021-12-10 17:30 UTC, keflavich commented
superceded by #776 .  Which really just highlights that issue trackers... don't work if you don't read them.

2021-12-10 17:30 UTC, closed without merging