Allow general filter use instead of just median filters
radio-astro-tools/spectral-cube pull request #812
Opened 2022-05-12 16:36 UTC by keflavich

Is there a nicer way to inherit the docstrings?

2022-06-13 00:29 UTC, keflavich commented
Ready for review

This PR basically just allows other filters to be used.  I needed this for some reason I can't remember recently.... I think I wanted a percentile filter or something?

2022-06-13 13:43 UTC, e-koch requested changes
Added some clarifying suggestions for the input parameters, and I think we should add a matching max filter test for spatial smoothing.

I'm fairly sure we don't need to loop over the whole range of ndimage filters; I think they should all return a ND array.

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/dask_spectral_cube.py
> +            A filter from scipy.ndimage.filters
```suggestion
            A filter from `scipy.ndimage.filters <https://docs.scipy.org/doc/scipy/reference/ndimage.html#filters>`_.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/dask_spectral_cube.py
> +        Smooth the cube along the spectral dimension using a filter
```suggestion
        Smooth the cube along the spectral dimension using a scipy.ndimage filter.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +            A filter from scipy.ndimage.filters
```suggestion
            A filter from scipy.ndimage.filters. The default is the median filter.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +            A filter from scipy.ndimage.filters
```suggestion
            A filter from `scipy.ndimage.filters <https://docs.scipy.org/doc/scipy/reference/ndimage.html#filters>`_.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +            Size of the median filter (scipy.ndimage.filters.*_filter)
```suggestion
            Size of the filter in pixels (scipy.ndimage.filters.*_filter).
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +        Smooth the image in each spatial-spatial plane of the cube using a filter.
```suggestion
        Smooth the image in each spatial-spatial plane of the cube using a scipy.ndimage filter.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +        Smooth the cube along the spectral dimension using a filter
```suggestion
        Smooth the cube along the spectral dimension using a scipy.ndimage filter.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +            Size of the median filter (scipy.ndimage.filters.median_filter)
```suggestion
            Size of the filter in spectral channels.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/spectral_cube.py
> +            Size of the median filter (scipy.ndimage.filters.*_filter)
```suggestion
            Size of the median filter in pixels (scipy.ndimage.filters.median_filter)
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/dask_spectral_cube.py
>              Size of the median filter (scipy.ndimage.filters.median_filter)
```suggestion
            Size of the filter in pixels.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/dask_spectral_cube.py
> +            A filter from scipy.ndimage.filters
```suggestion
            A filter from `scipy.ndimage.filters <https://docs.scipy.org/doc/scipy/reference/ndimage.html#filters>`_.
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/dask_spectral_cube.py
>              Size of the median filter (scipy.ndimage.filters.median_filter)
```suggestion
            Size of the median filter in spectral channels (scipy.ndimage.filters.median_filter).
```

2022-06-13 13:43 UTC, e-koch commented on spectral_cube/tests/test_spectral_cube.py
> +def test_spectral_smooth_maxfilter(num_cores, data_adv, use_dask):
We should have one more test like this for spatial smoothing.

2022-09-23 22:05 UTC, e-koch approved these changes

2022-09-23 22:12 UTC, merged