Add cube mosaicking
radio-astro-tools/spectral-cube pull request #829
Opened 2022-07-20 17:13 UTC by SpacialTree

Created functions to mosaic cubes together.

2022-07-22 00:23 UTC, keflavich requested changes
Thanks @SpacialTree!  This is a great addition.

I have requested some minor changes.

I also suggest we do one more serious restructuring: Instead of `reproject_together` returning the reprojected cubes, it would be best to have a function that returns the common Header to project to.  Then, we could do the mosaicking in the `mosaic_cubes` function.

There are a few reasons to adopt this approach, most having to do with when you want to mosaic more than two cubes together.  The function of finding the common grid to project to should be fast, even for many cubes, so it helps to separate it out.

Then both the `reproject_together` and the `mosaic_cubes` functions could take lists of cubes rather than just two cubes.

Eventually (not in this PR, but in a followup) we will want to allow the user to pass in a `mmap` array to project into and/or create `mmap` arrays so that the projection can be done when the cubes are larger than memory.  That will require using the [create a large fits file from scratch](https://docs.astropy.org/en/stable/generated/examples/io/skip_create-large-fits.html) code.

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    Two spectral cubes to reproject to the same wcs.
Rewrite this as a complete sentence.  What is the function doing?

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    cube1.allow_huge_operations=True
Minor code style fix
```suggestion
    cube1.allow_huge_operations = True
```

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    wcs_opt, shape_opt = find_optimal_celestial_wcs([(w1, s1),(w2, s2)], auto_rotate=False)
minor code style fix
```suggestion
    wcs_opt, shape_opt = find_optimal_celestial_wcs([(w1, s1), (w2, s2)], auto_rotate=False)
```

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    # Get the optimal wcs and shape for both fields together
Minor: it helps to mix in some whitespace before each block, probably before each of the comments, e.g.:
```suggestion

    # Get the optimal wcs and shape for both fields together
```

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    cube_repr2 = cube2.reproject(header, block_size=[100,cube2.shape[1], cube2.shape[2]])
Let's make this `100` a keyword argument, say, `spectral_block_size=100` as the default
```suggestion
    cube_repr1 = cube1.reproject(header, block_size=[spectral_block_size, cube1.shape[1], cube1.shape[2]])
    cube_repr2 = cube2.reproject(header, block_size=[spectral_block_size, cube2.shape[1], cube2.shape[2]])
```

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    Two spectral cubes to mosaic together.
same as above.  e.g., "This function projects two cubes onto a common grid and combines them."

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +def mosaic(cube1, cube2):
We need a somewhat more descriptive name - probably `mosaic_cubes`?

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    final_array = np.zeros(cube_repr1.shape)
This is fine for now, but this is where we might want to start using `mmap`s to enable reprojection out of memory.

That motivates a restructuring I'll describe in the overall review summary

2022-07-22 00:23 UTC, keflavich commented on spectral_cube/cube_utils.py
> +            final_array[s] = np.divide(np.add(slice1, slice2),mask_opt)
Minor style: we prefer >=2 character variable names
```suggestion
        for ii in range(final_array.shape[0]):
            slice1 = np.nan_to_num(cube_repr1[s])
            slice2 = np.nan_to_num(cube_repr2[s])
            final_array[ii] = np.divide(np.add(slice1, slice2),mask_opt)
```

2022-08-05 18:37 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    cube1.allow_huge_operations = True
Best not to do this.  It's up to the user to specify this before passing in the arguments.  Also, you've only done this for cube 1, but you'd need to for each.

2022-08-05 18:38 UTC, keflavich commented on spectral_cube/cube_utils.py
> +    shape_opt = (header['NAXIS3'],header['NAXIS2'],header['NAXIS1'])
minor thing, but our code style checker will enforce this (you need spaces after commas)
```suggestion
    shape_opt = (header['NAXIS3'], header['NAXIS2'], header['NAXIS1'])
```

2022-08-05 18:39 UTC, keflavich commented on spectral_cube/cube_utils.py
> +            slice2 = final_array[ii]
this isn't used
```suggestion
```

2022-08-05 18:40 UTC, keflavich commented on spectral_cube/cube_utils.py
> +            final_array[ii] = np.add(final_array[ii], slice1)
This is fine, but could also be
```suggestion
            final_array[ii] += slice1
```

2022-08-05 18:40 UTC, keflavich commented on spectral_cube/cube_utils.py
> +            final_array[ii] = np.add(final_array[ii], slice1)
I think my way will avoid creating a new copy in memory

2022-08-05 18:41 UTC, keflavich commented on spectral_cube/cube_utils.py
> +            final_array[ss] = np.divide(final_array[ss], mask_opt)
```suggestion
            final_array[ss] /= mask_opt
```

2022-08-16 19:26 UTC, SpacialTree commented
@keflavich Ready for further review!

2022-08-17 22:43 UTC, keflavich commented
It's time to start looking at the error messages.  For example, this is a syntax error:
https://github.com/radio-astro-tools/spectral-cube/runs/7883143970?check_suite_focus=true#step:5:162

2022-08-17 22:44 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +    @pytest.mark.parametrize('use_memmap', (True, False))
```suggestion
@pytest.mark.parametrize('use_memmap', (True, False))
```

2022-08-17 22:44 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +
```suggestion
```

2022-08-17 22:44 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +    assert (cube).wcs.compare(result.wcs.wcs)
```suggestion
    assert cube.wcs.compare(result.wcs.wcs)
```

2022-08-17 22:45 UTC, keflavich commented on spectral_cube/lower_dimensional_structures.py
> +                print("Encountered errors when creating image:", e)
Could you remove this change from this PR?  It's not related to the main issue here, so we'd like to have it in a separate PR

2022-08-18 22:26 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +    result = mosaic_cubes([part1, part2])
you need to import `mosaic_cubes` at the top of this file

2022-08-23 23:48 UTC, keflavich commented
We need to have the test skipped if reproject is not installed

2022-08-23 23:49 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +def test_mosaic_cubes(use_memmap, data_adv, use_dask):
```suggestion
def test_mosaic_cubes(use_memmap, data_adv, use_dask):

   pytest.importorskip('reproject')

```

2022-08-24 00:08 UTC, keflavich commented on spectral_cube/cube_utils.py
> +        cube_repr = cube.reproject(header, block_size=[spectral_block_size, cube.shape[1], cube.shape[2]])
Unfortunately `reproject` doesn't accept the `block_size` keyword yet (except in the development version), so we'll have to do something like:
```suggestion
        try:
            cube_repr = cube.reproject(header, block_size=[spectral_block_size, cube.shape[1], cube.shape[2]])
        except KeyError:
            warnings.warn("The block_size argument is not accepted by `reproject`.  A more recent version may be needed.")
            cube_repr = cube.reproject(header)

```

2022-08-24 00:08 UTC, keflavich commented on spectral_cube/tests/test_regrid.py
> +   pytest.importorskip('reproject')
bad indentation
```suggestion
    pytest.importorskip('reproject')
```

2022-08-24 00:10 UTC, keflavich commented on spectral_cube/cube_utils.py
> +        cube_repr = cube.reproject(header, block_size=[spectral_block_size, cube.shape[1], cube.shape[2]])
This should solve https://github.com/radio-astro-tools/spectral-cube/runs/7984859690?check_suite_focus=true#step:5:684

2022-08-24 16:02 UTC, keflavich commented
OK we're really close now, but the WCSes don't match up
https://github.com/radio-astro-tools/spectral-cube/runs/7996917393?check_suite_focus=true#step:5:596

2022-09-09 19:32 UTC, SpacialTree commented
There is an issue where the edge pixels of the image are turned into NaNs when reprojected. For very small cubes, such as those used in tests, this may result in the entire cube being turned into NaNs. 

![edges](https://user-images.githubusercontent.com/23216784/189429369-eaccc1b4-2ad7-4da9-8f79-d14629e0e850.png)


Code to reproduce:
```
from spectral_cube import SpectralCube
import numpy as np
import matplotlib.pyplot as plt

# Read in a spectral cube
cubename = '/orange/adamginsburg/cmz/g5/G5/sum/newcombination/g5.H2CO.spw23_test.fits' # Example data
cube = SpectralCube.read(cubename)

# Make 2D example so it will run faster, same result of edges being lost when using a cube
mom0 = cube.moment0() # Moment 0 of original cube
repro_mom0 = mom0.reproject(mom0.header) # Reproject Moment 0 to same header

# Get the masks of the Moment 0's (there is no get_mask_array for Projection objects)
mom0_mask = np.isfinite(mom0)
repro_mom0_mask = np.isfinite(repro_mom0)

# Find where the masks are different with xor
edges = np.logical_xor(mom0_mask, repro_mom0_mask)

# Plot an image of the edges
plt.imshow(edges)
```

2022-09-09 19:54 UTC, keflavich commented
Good catch.  This isn't really a bug as much as an annoying feature.  I think we can work around it by specifying `order='nearest-neighbor'` in the call to reproject.

2022-09-09 21:07 UTC, SpacialTree commented
Looks like that fixed the issue for moment 0's, but not for cubes. 

Try this for a cube:
```python
from spectral_cube import SpectralCube
import numpy as np
import matplotlib.pyplot as plt

# Read in a spectral cube
cubename = '/orange/adamginsburg/cmz/g5/G5/sum/newcombination/g5.H2CO.spw23_test.fits' # Example data
cube = SpectralCube.read(cubename)

cutcube = cube[:1]
repro_cutcube = cutcube.reproject(cutcube.header)

cutcube_mask = np.isfinite(cutcube)
repro_cutcube_mask = np.isfinite(repro_cutcube)

edges = np.logical_xor(cutcube_mask, repro_cutcube_mask)

plt.imshow(edges[0])
```

2022-09-09 21:11 UTC, keflavich commented
Still looks ok if you pass `reproject(..., order='nearest-neighbor')`, no?

2022-09-16 11:38 UTC, keflavich commented
It looks like tests are failing only on windows, so this is now good to go.  However, I want to see if I can fix the windows tests first (I think `main` is also failing on windows now)

2022-09-23 22:31 UTC, keflavich commented
I manage to fix the tests on windows, but now something has gone very weird with this PR - there is some documentation stuff showing up that has no right to be.

2022-09-30 18:48 UTC, keflavich commented
We're seeing the 'all-nans' errors on Windows only, I think, but it is coming from this PR.

2022-09-30 19:34 UTC, keflavich commented
OK, I've pinned this down to a really obscene error:
```python
(Pdb) wcs_out.spectral.pixel_to_world(np.arange(6))
<SpectralCoord
   (doppler_rest=0.0 m
    doppler_convention=optical)
  [-321214.698632  , -319926.48366321, -318638.26869442, -317350.05372563,
   -316061.83875684, -314773.62378805] m / s>
(Pdb) wcs_in.spectral.world_to_pixel(wcs_out.spectral.pixel_to_world(np.arange(6)))
array([nan, nan, nan, nan, nan, nan])
```

which arises because of a deep, stupid, painful bug in WCS:
```
(Pdb) wcs_in.wcs.restfrq
1420405718.41
(Pdb) wcs_in.wcs.restwav
0.0
```
the solution is apparently to hack in a restwav...

2022-09-30 19:57 UTC, keflavich commented
https://github.com/astropy/astropy/issues/13774 is the issue that caused our nan problems.

2022-10-03 18:06 UTC, keflavich commented
Well dangit, that's the same error.

2022-10-03 19:43 UTC, keflavich commented
@astrofrog @e-koch we're getting "file not closed" errors in addition to other unexpected errors.  Any idea why?  It's in test_reproject.
https://github.com/radio-astro-tools/spectral-cube/actions/runs/3176766813/jobs/5176439021#step:5:235

I can't reproduce the other errors, which is disconcerting.  Looks like dev versions are the problem, so I'll try again with newer astropy etc.

2022-10-03 22:48 UTC, keflavich commented
Nevermind the previous message - the "Errors" were caused by the legitimate failures.  All green now!

@e-koch want a final look?  I'm good to merge now

2022-10-03 22:49 UTC, keflavich approved these changes

2022-10-03 23:00 UTC, e-koch approved these changes
Just a couple minor things. This looks great @SpacialTree!

@keflavich I'm happy to merge with these minor changes.

2022-10-03 23:00 UTC, e-koch commented on spectral_cube/cube_utils.py
> +            slice1 = np.nan_to_num(cube_repr[ii].value)
It's minor but this may be a bit more efficient:
```suggestion
            slice1 = np.nan_to_num(cube_repr.unitless_filled_data[ii])
```

2022-10-03 23:00 UTC, e-koch commented on spectral_cube/cube_utils.py
> +    # TODO: this should use the same cube type as cube1
Double check this is now addressed in the next line (I think so).

2022-10-03 23:00 UTC, e-koch commented on spectral_cube/tests/test_regrid.py
> +    # Check that values of original and result are comaprable
```suggestion
    # Check that values of original and result are comparable
```

2022-10-04 11:51 UTC, merged