Regression fix: if how='slice' or 'ray', we do _not_ want to warn
radio-astro-tools/spectral-cube pull request #929
Opened 2024-10-20 18:01 UTC by keflavich

https://github.com/radio-astro-tools/spectral-cube/pull/916 introduced a serious regression: `warn_slow` now completely ignores `how='slice'` and `how='ray'`, which was not at all the desired behavior.

2025-01-06 16:44 UTC, keflavich commented
I could use some feedback here @astrofrog @e-koch : I've removed warnings about dask loading whole cubes into memory, but I'm second-guessing myself now.  When you do cube addition, what other option is there than to keep the whole cube in memory?

On the other hand, should we just drop the warnings entirely?  I am not sure they're ever appreciated or valuable.  This is a bigger question, but for my own use, most of the time I do everything to suppress these warnings...

2025-01-06 21:41 UTC, keflavich commented
This passes completely if I run a local test:
```
$ pytest spectral_cube
============================================================================================================= test session starts =============================================================================================================
platform darwin -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0
Running tests in spectral_cube.

Date: 2025-01-06T16:30:52

Platform: macOS-13.6-arm64-i386-64bit

Executable: /Users/adam/mambaforge/envs/py312/bin/python3.12

Full Python Version:
3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions:
Numpy: 2.1.2
Scipy: 1.14.0
Matplotlib: 3.9.2
h5py: 3.11.0
Pandas: 2.2.3
Astropy: 6.1.2
regions: 0.10
APLpy: not available

Using Astropy options: remote_data: none.

rootdir: /Users/adam/repos/spectral-cube
configfile: setup.cfg
plugins: astropy-0.11.0, cov-5.0.0, remotedata-0.4.1, rerunfailures-14.0, filter-subpackage-0.2.0, doctestplus-1.2.1, astropy-header-0.2.2, dependency-0.6.0, anyio-4.4.0, hypothesis-6.111.1, arraydiff-0.6.1, asdf-3.4.0, mock-3.14.0, dash-2.18.2
collected 1721 items

spectral_cube/spectral_axis.py .                                                                                                                                                                                                        [  0%]
spectral_cube/tests/test_analysis_functions.py ...................                                                                                                                                                                      [  1%]
spectral_cube/tests/test_casafuncs.py ......sssssssssssssss                                                                                                                                                                             [  2%]
spectral_cube/tests/test_cube_utils.py .......                                                                                                                                                                                          [  2%]
spectral_cube/tests/test_dask.py .....s.......s.                                                                                                                                                                                        [  3%]
spectral_cube/tests/test_io.py .......................                                                                                                                                                                                  [  4%]
spectral_cube/tests/test_masks.py .....................................................................................XX....                                                                                                           [ 10%]
spectral_cube/tests/test_moments.py ............................................................................................................................................................................................        [ 21%]
spectral_cube/tests/test_performance.py ...s..                                                                                                                                                                                          [ 21%]
spectral_cube/tests/test_projection.py .......................x..............xxx.......x..........................................................................                                                                      [ 28%]
spectral_cube/tests/test_regrid.py ........................................................                                                                                                                                             [ 31%]
spectral_cube/tests/test_spectral_axis.py ....................................................                                                                                                                                          [ 34%]
spectral_cube/tests/test_spectral_cube.py ............................................................................................................................................................................................. [ 45%]
.......................................................................................s.....s...........sssss.................................................ssssss......................ss.......................................... [ 59%]
................................................................................ssssss......ssssssssssss......ssssssssssss......ssssssssssss......ssssssssssss......ssssss............................................................. [ 72%]
.............................ssssss......ssssssssssss......ssssssssssss......ssssssssssss......ssssssssssss......ssssss.................................s.s..............xxxx.......................................................... [ 86%]
..........ssss............................xxxxxxxx.........................................                                                                                                                                             [ 91%]
spectral_cube/tests/test_stokes_spectral_cube.py ....................................................................................................                                                                                   [ 97%]
spectral_cube/tests/test_subcubes.py ......................                                                                                                                                                                             [ 98%]
spectral_cube/tests/test_visualization.py ....ssss..ss                                                                                                                                                                                  [ 99%]
spectral_cube/tests/test_wcs_utils.py ............                                                                                                                                                                                      [100%]

==================================================================================== 1537 passed, 165 skipped, 17 xfailed, 2 xpassed in 287.50s (0:04:47) ====================================================================================
```

but I reproduce the exact failure with tox.  I don't understand it.

2025-01-06 23:15 UTC, e-koch commented
For the cube addition: are we defaulting to a new memory map or zarr for the dask versions? If so, I don't see a particular issue with dropping the warnings.

2025-01-06 23:22 UTC, keflavich commented
regarding the casa reading failures: I'm not sure the above is a 'real life' bug and not just something weird about the tox system.

2025-01-06 23:23 UTC, keflavich commented
cube addition: I think it's a new in-memory array.  But if we default to a new memmap, I'd be happier with that.... is that a thing we can do?  We have to tell numpy to do it...

2025-01-07 16:10 UTC, keflavich commented
Green on all but the CASA tests, for which it seems a STOKES keyword has gone missing.  @preshanth, could you have a look?

2025-01-07 22:52 UTC, preshanth commented
The issue seems to be that the cubes being used in the test have no stokes axis. These are perfectly valid cubes. You can see from the `desc` header values here is the one where the tests are failing.
``` ['telescope', 'observer', 'obsdate', 'pointingcenter', 'telescopeposition', 'direction0', 'worldmap0', 'worldreplace0', 'pixelmap0', 'pixelreplace0', 'spectral1', 'worldmap1', 'worldreplace1', 'pixelmap1', 'pixelreplace1'] ```
We are searching for `stokes1`. The way casa arranges the headers is it checks for direction, then stokes and then spectral. If there is no stokes found we can default to Stokes I and throw a warning and proceed. That would take care of this issue.

2025-01-07 23:11 UTC, preshanth commented
I did this and it gets over the error altogether. 
```
        # check if stokes1 or stokes 2 is present. if not assume stokes_params = ['I']
        if 'stokes1' in desc['_keywords_']['coords']:
            stokes_params = desc['_keywords_']['coords']['stokes1']['stokes']
        elif 'stokes2' in desc['_keywords_']['coords']:
            stokes_params = desc['_keywords_']['coords']['stokes2']['stokes']
        else:
            # throw a warning
            warnings.warn("No stokes information found in CASA image. Assuming Stokes I.")
            stokes_params = ['I']```
This should cover most cubes unless people come up with a really crazy stokes cube. I will try and cook one of those up in the meantime. I have to see what the fits standard allows.

2025-01-09 00:12 UTC, e-koch requested changes
Looks good. One minor change to get rid of a couple print statements before merging.

2025-01-09 00:12 UTC, e-koch commented on spectral_cube/io/casa_image.py
>          print(desc['_keywords_']['coords'])
Remove temp print statements

2025-01-17 01:34 UTC, e-koch approved these changes

2025-01-17 01:53 UTC, e-koch commented
The previous test failures all pass. The new failure is related too #936 from an unrelated update in zarr. We'll address that issue separately.

2025-01-17 01:53 UTC, merged